
services:
  - type: web
    name: molde-polo-flask
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: development
